### ISSUE TITLE
Wrong starting point in floor plan, dollhouse issues, and marker issues

### ISSUE THREAD

**Issue by HeroponRikiBestest** [rebane2001/matterport-dl#10]
Using 3rmnPWnWbhh:

- The downloaded file starts you in the wrong place
Original URL-
![image](https://user-images.githubusercontent.com/50224630/140633932-30140e5d-09f3-41a4-b766-de1c2a8aca9e.png)
Downloaded files-
![image](https://user-images.githubusercontent.com/50224630/140633937-599b424a-6f16-4cbc-a320-6d268c2485b8.png)

- The dollhouse has bad/messed up textures
Original URL-
![image](https://user-images.githubusercontent.com/50224630/140633957-d07524ff-205d-4b97-bb73-68816f74bc4f.png)
Downloaded files-
![image](https://user-images.githubusercontent.com/50224630/140633962-fcbfa608-d147-4425-ac1c-b2425bb667d2.png)
(If this is just a repeat of https://github.com/rebane2001/matterport-dl/issues/8, feel free to disregard)

- Marker issues
I won't post any pictures for this, as you can see from the dollhouse photos that the markers attached to various objects throughout the tour have been misaligned from their original locations (this remains true if you exit the dollhouse view and go "inside" the rooms). Additionally, many are missing. Upon further inspection, these markers actually appear to be from a completely different listing (no idea which one)- the markers that are inbounds on the downloaded file appear to be talking about some unrelated topics, (magazines, typesetting, people traveling asia, floor plans?) while all the markers on the original url talk about the various arcade machines present at this location, and link to various tweets and youtube videos from their social medias.

**Comment by mitchcapper** [comment]
Markers, the info text, and start data is all a new feature (good job running head) from the merge earlier today.  Sadly in coding it I didn't adjust per model properly.  PR shortly should fix this.  I tested your exact model with the revisions and they all seemed to work.

![image](https://user-images.githubusercontent.com/1643324/140638168-959a71fe-f1bb-4a00-9cc9-c72db0415c70.png)
![image](https://user-images.githubusercontent.com/1643324/140638177-c21f3004-6697-4d58-8da1-ebb9d5224a9c.png)


Texture issue is #8

**Comment by HeroponRikiBestest** [comment]
Running head?

Anyways, thank you so much! Out of curiosity, is there any option to download external resources (i.e. tweets, youtube videos, other assorted pages) linked to by various markers, so that the embeds and the outlinks can still work offline?

**Comment by mitchcapper** [comment]
Sorry, meant to say thanks for running the very latest version as we just added that:)  Also watch issue #8 there will be a PR to fix that as well.

**Comment by HeroponRikiBestest** [comment]
Awesome, thank you! Any idea if there will be any option to download external resources (i.e. tweets, youtube videos, other assorted pages) linked to by various markers, so that the embeds and the outlinks can still work offline?
