### ISSUE TITLE
Attachments aren't being downloaded

### ISSUE THREAD

**Issue by RandomStrangerOnTheInternet** [rebane2001/matterport-dl#101]
![image](https://github.com/rebane2001/matterport-dl/assets/47994830/4234ea1f-1e1d-4061-b153-da545284557d)

**Comment by vikaskedia** [comment]
Try using https://github.com/mu-ramadan/matterport-dl.git it is a fork of the current project and it is 24 commits ahead and works much better and has 53 stars.

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not.
