### ISSUE TITLE
Stuck Visualisation

### ISSUE THREAD

**Issue by WttBe** [rebane2001/matterport-dl#103]
Hello,

I finally got the visualisation to load (the model had to be in the same folder as the matterport-dl file), but the model freezes after a random number of seconds. I can not use the buttons, options, and move anymore, but I can still look around. I did not find any mention of that in the previous issues. Is there anything else I can provide to ease the finding of a solution?

Best regards,

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not.

**Comment by WttBe** [comment]
Hello,

Thanks, I'll try it again ASAP.

Best regards,
