### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hloren-m** [rebane2001/matterport-dl#105]
Downloading base page...
https://cdn-2.matterport.com/models/170fb7ee0b9e4ab3bab5e873504571c7/assets/~/{filename}?t=2-113159099119bf4c5a576b0fb4632823c5fe04b4-1703428805-1
Downloading static assets...
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 217.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 231.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 27.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 324.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 325.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 327.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 33.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 330.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 378.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 401.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 477.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 62.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 625.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 648.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 662.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 679.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 782.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 858.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 933.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 948.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 952.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 958.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 983.js, will download for you though:)

**Comment by zwsq** [comment]
I have the same problem. I downloaded the project with --advanced-download switch and it has finished successfully.  Then I tried to run the project on localhost and I saw the project does not load in the browser and in python console I got some 404 for specific files. I read the **run_report.log** and there are lots of 404 and 403 error while downloading the files. This is for the most recent project and for the previous ones still work fine. I think rate limiting is implemented on matterport CDN and it does not allow downloading file rapidly.
![image](https://github.com/rebane2001/matterport-dl/assets/46836427/68c090bb-e341-4745-bfe9-2a352f3b98b7)
![image](https://github.com/rebane2001/matterport-dl/assets/46836427/3821c35e-9190-4fdc-b431-a922d87e8407)
![image](https://github.com/rebane2001/matterport-dl/assets/46836427/683bf170-d037-46e9-83e3-6b506eea3ee8)

**Comment by vikaskedia** [comment]
Try using https://github.com/mu-ramadan/matterport-dl.git it is a fork of the current project and it is 24 commits ahead and works much better and has 53 stars.

**Comment by thdoan** [comment]
> Try using https://github.com/mu-ramadan/matterport-dl.git it is a fork of the current project and it is 24 commits ahead and works much better and has 53 stars.

YMMV. Fork doesn't work on 58kFEzB9k7x, for example.

**Comment by mitchcapper** [comment]
Pleased to say our latest update seems to have everything here working with 58kFEzB9k7x served wonderfully.
