### ISSUE TITLE
Please add the following js

### ISSUE THREAD

**Issue by dreamflyer93** [rebane2001/matterport-dl#106]
As instructed by script:

JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 217.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 231.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 27.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 324.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 325.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 327.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 33.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 330.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 378.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 401.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 477.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 62.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 625.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 648.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 662.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 679.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 782.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 858.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 933.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 948.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 952.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 958.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 983.js, will download for you though:)

**Comment by jmgomezpoveda** [comment]
This may have been superseded by https://github.com/rebane2001/matterport-dl/issues/110

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not.
