### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'api/mp/models/graph_GetModelDetails.json'

### ISSUE THREAD

**Issue by Secret779** [rebane2001/matterport-dl#108]
Comes up with loading screen when opening http://127.0.0.1:8080 and it doesn't change from there, even with cmd prompt open.
Error visible is 
FileNotFoundError: [Errno 2] No such file or directory: 'api/mp/models/graph_GetModelDetails.json'

I was wondering if I could have help? Trying to download childhood home I'm moving from! Thank you :')

**Comment by SportsApps** [comment]
Unfortunately I'm experience the same issue:

Traceback (most recent call last):
  File "/Users/macbookpro/matterport-dl.py", line 690, in <module>
    initiateDownload(pageId)
  File "/Users/macbookpro/matterport-dl.py", line 555, in initiateDownload
    downloadPage(getPageId(url))
  File "/Users/macbookpro/matterport-dl.py", line 545, in downloadPage
    patchGetModelDetails()
  File "/Users/macbookpro/matterport-dl.py", line 314, in patchGetModelDetails
    with open(f"api/mp/models/graph_GetModelDetails.json", "r", encoding="UTF-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'api/mp/models/graph_GetModelDetails.json'

Could please someone help us with it?

Best

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not.
