### ISSUE TITLE
Please, Add the following JS

### ISSUE THREAD

**Issue by serpro** [rebane2001/matterport-dl#110]
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 217.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 231.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 27.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 324.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 325.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 327.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 378.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 401.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 425.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 477.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 62.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 625.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 648.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 653.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 672.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 679.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 746.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 782.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 858.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 933.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 948.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 958.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 973.js, will download for you though:)

**Comment by terabyte** [comment]
I can confirm, trying to download a 3d tour from redfin I got this same output, and viewing it doesn't seem to work now.

**Comment by terabyte** [comment]
I added these numbers to the list but I am still having trouble viewing it, so there may be something else going on

**Comment by maxnbk** [comment]
My output is identical, sadly, same filenames.

**Comment by mitchcapper** [comment]
thanks, handled!
