### ISSUE TITLE
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add ...

### ISSUE THREAD

**Issue by valeriorobert** [rebane2001/matterport-dl#113]
Downloading static assets...
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 17.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 176.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 217.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 225.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 231.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 27.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 280.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 314.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 324.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 325.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 327.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 477.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 529.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 548.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 622.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 625.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 648.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 679.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 717.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 782.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 858.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 958.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 968.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 969.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 973.js, will download for you though:)

**Comment by mitchcapper** [comment]
thanks, handled!
