### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by HeroponRikiBestest** [rebane2001/matterport-dl#14]
Upon trying to run the latest update:
`bestest@bestest-ThinkPad-T14-Gen-1:~/matterport-dl$ python3.9 matterport-dl.py 
  File "/home/bestest/matterport-dl/matterport-dl.py", line 356
    raw_path, _, query = self.path.partition('?')
TabError: inconsistent use of tabs and spaces in indentation
`

**Comment by rebane2001** [comment]
Fixed, update the script
