### ISSUE TITLE
[Bug]: model not available

### ISSUE THREAD

**Issue by binarypower2** [rebane2001/matterport-dl#140]
### One or more sample matterport IDs / urls that reproduce the issue

928Bx83snkc

### Started up message

Started up a download run Running python 3.13.0 on win32

### Python version

3.13.0

### Steps to reproduce

matterport-dl.py https://my.matterport.com/show/?m=928Bx83snkc 

finished with the following:

Done, Total fetches: 68853 Skipped: 181 (0%) actual Request: 68672 (100%) Success: 68476 (99%) Failed403: 173 (0%) Failed404: 23 (0%) FailedUnknown: 0 (0%)!

### What went wrong

when i tried to view 
matterport-dl.py https://my.matterport.com/show/?m=928Bx83snkc 127.0.0.1 8080

it said 
Oops, model not available.
If the problem persists see our [troubleshooting guide](https://support.matterport.com/s/article/Oops-Model-Not-Available).

**Comment by mitchcapper** [comment]
Fixed they added a new CSS file. You do not need to redownload the entire model just re-run the download run and use `--no-main-asset-download` it should download the one new file and you should be good to go.
