### ISSUE TITLE
[Bug]: Unable to host offline

### ISSUE THREAD

**Issue by redstreet** [rebane2001/matterport-dl#142]
### One or more sample matterport IDs / urls that reproduce the issue

EGxFGTFyC9N

### Can you reproduce this issue with the sample small digital twin https://my.matterport.com/show/?m=EGxFGTFyC9N

Yes

### Started up message

Started up a download run Running python 3.12.3 on linux with matterport-dl version: refs/heads/main (850e2acbb013db4e43f24dc79c42b2bdfca800af)    

### Steps to reproduce

```
./matterport-dl.py EGxFGTFyC9N 
# Turn Wifi off on laptop
./matterport-dl.py EGxFGTFyC9N 127.0.0.1 8080
```

### What went wrong

The browser page is blank. I tried this on Chrome, Chromium, and Edge.

However, if I turn on the Wifi and refresh, everything works fine and the model comes up. This is the case for any model I try. How can I debug this further? Thank you!

**Comment by mitchcapper** [comment]
Turn off wifi.  Start hosting a model.   Open a browser/new tab but don't go anywhere.  Hit F12 to bring up developer tools.  Go the networks tab in the developer tools.   Now browse to the model (ie http://127.0.0.1:8080).   It should go white as you mention, now low look at developer tools again and in the network tab hopefully we have one or more error requests to a non 127.0.0.1 address.   

Note dev tools in chrome by default doesn't show the url you have to right click on the columns and click URL.

Assuming we do get some errors please post the urls.

**Comment by redstreet** [comment]
Awesome, thank you for this! Followed your instructions, and found one error with a non 127.0.0.1 address:

```
https://static.matterport.com/webgl-vendors/three/0.151.3/three.min.js
```

**Comment by mitchcapper** [comment]
Redownload and you should be good to go.

**Comment by redstreet** [comment]
Terrific, works perfectly now! Thank you for the quick response, and thanks a ton for developing, maintaining sharing this, which has been very useful!
