### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by forteuropa** [rebane2001/matterport-dl#144]
### One or more sample matterport IDs / urls that reproduce the issue

error

### Can you reproduce this issue with the sample small digital twin https://my.matterport.com/show/?m=EGxFGTFyC9N

I Don't Know, did not take the time to test it

### Python version

3.10.12

### Steps to reproduce

When running python3 matterport-dl.py, I get syntax error 

### What went wrong

 When running python3 matterport-dl.py, I get the following error: 
 
  File "/home/fort/workspace/matterport/matterport-dl/matterport-dl.py", line 548
    plugPath = f"showcase-sdk/plugins/published/{plugin["name"]}/{plugin["currentVersion"]}/plugin.json"

**Comment by mitchcapper** [comment]
Update python not at minimum version.
