### ISSUE TITLE
[Bug]: AccessKey expires during parsing of large Matterport tours

### ISSUE THREAD

**Issue by LevonX** [rebane2001/matterport-dl#148]
### One or more sample matterport IDs / urls that reproduce the issue

ZaLhNdDsQBm

### Can you reproduce this issue with the sample small digital twin https://my.matterport.com/show/?m=EGxFGTFyC9N

No

### Python version

3.12

### Steps to reproduce

- Start the script with or without proxies.
- Observe that after 5 minutes, files fail to download due to accesskeys expiration.

### What went wrong

When attempting to parse and download files for very large Matterport tours, the script encounters an issue where the accesskeys(?t=) expires before all files can be downloaded. The accesskeys has a lifespan of only 5 minutes (e.g. in tilesets, meshes, textures), which is insufficient for tours containing tens of thousands of files, especially when proxies are being used.

This results in incomplete downloads.

Expected Behavior:
The script should handle AccessKey expiration gracefully, either by renewing the key when it expires.

**Comment by LevonX** [comment]
`ERROR    aFailure REQ for ADV_SKYBOX 5189: should exist: False Result: Error of: HTTP Error 410:  File: models/8f92885ee1d747fd90db78ffa421e649/assets/pan/high/_/6a9b765d6970490bbfb5c69994b4cad5_skybox0.jpg at url: https://cdn-2.matterport.com/models/8f92885ee1d747fd90db78ffa421e649/assets/pan/high/~/6a9b765d6970490bbfb5c69994b4cad5_skybox0.jpg?t=2-15088fcff4544beafabd788c3011a2040805fa1b-1733298302-1&k=models%2F8f92885ee1d747fd90db78ffa421e649%2Fassets%2Fpan%2Fhigh
`

**Comment by LevonX** [comment]
Apparently Matterport changed the expiration date of the keys

**Comment by mitchcapper** [comment]
Interesting counter attempt on their part.   If someone wants to dig out their new token update code great.  Otherwise prolly not until start of Jan I can deep dive in.

**Comment by mitchcapper** [comment]
While annoying I assume if you re-run the same model it downloads more each time right? It should skip all the ones it already did.   I had to deal with some much larger changes from matterport ( #150 ) but will look at auto key renewal soon

**Comment by LevonX** [comment]
Yes, maybe a repeated parsing will finally download everything that is needed, but for large tours you need to repeat several dozen times.

I also see their updates and understand that parsing will be more and more difficult.

**Comment by mitchcapper** [comment]
Hi @LevonX I have massively changed up the access key usage I believe this should use a new key that has an expiry time >12 hours.  Let me know if this doesn't resolve your issue (it also does far less brute forcing for resources so should be faster to download large models).
