### ISSUE TITLE
Youtube videos on markers do not embed/link on downloaded listings

### ISSUE THREAD

**Issue by HeroponRikiBestest** [rebane2001/matterport-dl#15]
Self explanatory; markers that link to youtube videos do not properly do so.

Using 3rmnPWnWbhh as an example:
- Original link
![image](https://user-images.githubusercontent.com/50224630/140737737-e1474a49-5803-44de-927e-96bc2b97f814.png)

- Downloaded listing
![image](https://user-images.githubusercontent.com/50224630/140737450-794f1900-9dc7-491b-b694-ca5aff005d0b.png)

**Comment by mitchcapper** [comment]
I think this is fixed but 3rmnPWnWbhh has been deleted so please provide another if not.
