### ISSUE TITLE
Excessive DNS requests

### ISSUE THREAD

**Issue by Slyke** [rebane2001/matterport-dl#28]
When I run this, PiHole is complaining that my computer has been making too many DNS requests (default limit is 1000 in a 60 second time period). Setting my computer's DNS to some public one like 8.8.8.8 and bypassing PiHole mitigates this issue, but is it possible to have the Requests module cache matterport's IP address?

**Comment by mitchcapper** [comment]
generally your computer (or at least windows) and your dns server should both be caching the DNS information unless the record itself has a TTL that is  very short.  

In terms of the request this is beyond this project scope it would fall to the requests module which already says won't fix:
https://github.com/psf/requests/issues/1453
followed by urllib3 saying the same: https://github.com/urllib3/urllib3/issues/925

**Comment by Slyke** [comment]
Ah, okay! Fair enough. Thanks for answering!
