### ISSUE TITLE
Texture Mapping Errors

### ISSUE THREAD

**Issue by prestomation** [rebane2001/matterport-dl#31]
This is super awesome!

I tried to download one but the dollhouse textures are..all messed up.

Here is a screenshot from the download:
![image](https://user-images.githubusercontent.com/845970/148312821-a940fe80-bf8a-449a-9c6d-f4f13a1eafa9.png)

and here from the source:

![image](https://user-images.githubusercontent.com/845970/148312931-d7a01dfb-3655-47e9-b476-0baca27c92c7.png)

Is this a known issue? The matterport Id is shdeTtAQiX4

**Comment by mitchcapper** [comment]
please b sure to follow the readme and search the other bug reports https://github.com/rebane2001/matterport-dl/issues?q=dollhouse if still an issue let us know.

**Comment by prestomation** [comment]
Thanks. Doing the advanced download and then serving files using the script(instead of something like SimpleHTTPServer) seemed to have worked. I missed the note in the README
