### ISSUE TITLE
Feature: Add support for downloading matterport models that require authentication

### ISSUE THREAD

**Issue by rebane2001** [rebane2001/matterport-dl#37]
Quite self-explanatory, use cookies of a logged in account to perform the download.

Here is some sample code that I've confirmed working before with an early version of matterport-dl:
```py
# Put your cookies here in request format (can be found from your browser's devtools->network)
cookies = ""

# Install urllib opener that uses cookies
# Works for every `urllib.request.urlretrieve` already in the code
opener = urllib.request.build_opener()
opener.addheaders = [('cookie', cookies)]
urllib.request.install_opener(opener)

# Use cookies with the requests module
 r = requests.get(f"https://example.com", headers={'cookie':cookies})
```

Would also be a good idea to implement the cookies.txt format.

**Comment by loudgazelle** [comment]
I'm assuming the lack of authentication support would prevent me from using this to download videos from the my.matterport.com site, correct?

**Comment by mitchcapper** [comment]
If you cannot access the video without logging in yes you would need the above, the easier option is just make it unlisted rather htan private, download it, and the make it private again.

**Comment by loudgazelle** [comment]
The link was provided by my general contractor, I'll see if they have the ability to do that.

**Comment by rebane2001** [comment]
If it was just a link you could visit without signing in, then authentication is unnecessary.

**Comment by loudgazelle** [comment]
the link definitely makes me sign in using a password provided by the general contractor.

**Comment by mitchcapper** [comment]
there is integrated proxy support now for the downloader.  You could use a web proxy that supports manual cookie injection to potentially be able to login to private models (login in the browser then have the proxy add the cookies for matterport-dl).
At this time I do not believe we have plans for further authenticated downloading.
