### ISSUE TITLE
Error code: "ModuleNotFoundError: No module named 'requests'"

### ISSUE THREAD

**Issue by RayG2020** [rebane2001/matterport-dl#42]
I tried to download the tour from link: https://my.matterport.com/show/?m=qKHuSvYEF5N 

But after I input matterport-dl.py "https://my.matterport.com/show/?m=qKHuSvYEF5N"  I got the following feedback, could someone help me to identify the issue?

c:\Matterport>matterport-dl.py "https://my.matterport.com/show/?m=qKHuSvYEF5N"
Traceback (most recent call last):
  File "C:\Matterport\matterport-dl.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by rebane2001** [comment]
You need to install the dependencies:

    pip install requests
    pip install tqdm
