### ISSUE TITLE
JS file unknown

### ISSUE THREAD

**Issue by mikhoul** [rebane2001/matterport-dl#47]
![image](https://user-images.githubusercontent.com/5678673/156425581-6d883bdf-5d98-45db-8b6c-2ff86e2837ac.png)

If you need more information just ask me.

**Comment by dnlldl** [comment]
duplicate of https://github.com/rebane2001/matterport-dl/issues/45 ...

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
