### ISSUE TITLE
JS Files Unknown (463, 477, 521, 934)

### ISSUE THREAD

**Issue by UnixNight** [rebane2001/matterport-dl#48]
![image](https://user-images.githubusercontent.com/17035391/157311266-f076a8d7-44e4-4c19-9bfa-44d9a61d6017.png)

**Comment by UnixNight** [comment]
Different JS files compated to #45 and #47

**Comment by rebane2001** [comment]
Thank you!

**Comment by nuncidvides** [comment]
Today I'm getting this but for 475, 521, 856, 880, and 934

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
