### ISSUE TITLE
JS files extracted but not known: 475.js, 521.js, 856.js, 880.js, 934.js

### ISSUE THREAD

**Issue by sealsealsealsealsealseal** [rebane2001/matterport-dl#49]
These are the five files:

- 475.js
- 521.js
- 856.js
- 880.js
- 934.js

```
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 475.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 856.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 880.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 934.js, will download for you though:)
```

**Comment by jegelstaff** [comment]
FYI Same here

**Comment by JoaoG23** [comment]
FYI same for me

**Comment by ywwg** [comment]
me 5

**Comment by flogal** [comment]
Same here also

**Comment by lcd-dal** [comment]
Same issue

**Comment by rblakeman** [comment]
Same here

**Comment by mitchcapper** [comment]
Thanks all, if someone has mentioned the files that is good we just add those files to the next release to make sure we are nabbing everything. To be clear your local copy did pull them in and so you are not missing them.

**Comment by dpp** [comment]
Here are the unknown JS files I'm seeing:

```
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 170.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 300.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 393.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 55.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 631.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 856.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 934.js, will download for you though:)
```

**Comment by zura3395** [comment]
> Here are the unknown JS files I'm seeing:
> 
> ```
> JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 170.js, will download for you though:)
> JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 300.js, will download for you though:)
> JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 393.js, will download for you though:)
> JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
> JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 55.js, will download for you though:)
> JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 631.js, will download for you though:)
> JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 856.js, will download for you though:)
> JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 934.js, will download for you though:)
> ```

Seeing these as well.
![Screenshot 2022-04-23 180741](https://user-images.githubusercontent.com/68401942/164951380-30c7e877-fdc2-4906-9859-86b5a8030ca9.png)

**Comment by mb-weberon** [comment]
I am using the following version
https://github.com/rebane2001/matterport-dl/commit/e01449528bd5fe05f9362b633bd4fe33d7a4a3fa

and am seeing these too

Downloading static assets...
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 170.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 300.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 393.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 55.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 631.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 856.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 934.js, will download for you though:)
Downloading model info...

**Comment by Vaibhav-Vipin** [comment]
Here are some of the JS files I am seeing.
![error](https://user-images.githubusercontent.com/39304129/199658730-76a61eac-266a-49e0-8b8e-efa9de2651a8.png)

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
