### ISSUE TITLE
showcase.js: api/v1/event not found and failed to load es6Module 

### ISSUE THREAD

**Issue by josvanr** [rebane2001/matterport-dl#50]
Hello! 

I'm testing your script on a space from the matterport website

https://my.matterport.com/show/?m=Ez3YDocMaVx

Downloading the space works so far as I know. When viewing it locally, some files
are missing, like 415.js or something, I was able to get them manually using chrome 
devtools. There is another missing file however, api/v1/event that is not present. Not
sure what this is, or if it is actually a file. When viewing it in chrome devtools, it contains
this text:

{"code":"request.unsupported","message":"Unsupported Request"}

When I copy the file to api/v1/event, the 404 error disappears, but I still get errors from 
showcase.js, failed to load es6Module, among others (see image)

In which direction can I look to find a solution?

![1](https://user-images.githubusercontent.com/35400537/161234589-50db9af5-453e-4088-8e33-1aae94a05cc9.png)

the complete expanded list of errors from chrome console is here:

showcase.js:14 [module-loader] 0.469s Failed to load es6Module for Symbol(pano): TypeError: Cannot read properties of undefined (reading 'call')
(anonymous) @ showcase.js:14
Promise.catch (async)
loadModule @ showcase.js:14
loadModuleBySymbol @ showcase.js:14
load @ showcase.js:14
await in load (async)
loadApplication @ showcase.js:14
(anonymous) @ showcase.js:14
(anonymous) @ showcase.js:14
(anonymous) @ ?m=Ez3YDocMaVx:137
showcase.js:14 [engine] 0.469s TypeError: Cannot read properties of undefined (reading 'call')
    at o (showcase.js:14:445750)
    at Module.52061 (833.js:9:25596)
    at Function.o (showcase.js:14:445750)
loadApplication @ showcase.js:14
await in loadApplication (async)
(anonymous) @ showcase.js:14
(anonymous) @ showcase.js:14
(anonymous) @ ?m=Ez3YDocMaVx:137
showcase.js:14 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
    at o (showcase.js:14:445750)
    at Module.52061 (833.js:9:25596)
    at Function.o (showcase.js:14:445750)
o @ showcase.js:14
52061 @ 833.js:9
o @ showcase.js:14
Promise.then (async)
then @ showcase.js:14
loadModuleBySymbol @ showcase.js:14
load @ showcase.js:14
await in load (async)
loadApplication @ showcase.js:14
(anonymous) @ showcase.js:14
(anonymous) @ showcase.js:14
(anonymous) @ ?m=Ez3YDocMaVx:137
showcase.js:14 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
    at o (showcase.js:14:445750)
    at Module.52061 (833.js:9:25596)
    at Function.o (showcase.js:14:445750)
o @ showcase.js:14
52061 @ 833.js:9
o @ showcase.js:14
await in o (async)
notifyObserver @ showcase.js:2
notifyObservers @ showcase.js:2
notifyObservers @ showcase.js:2
notifyUp @ showcase.js:2
notifyUp @ showcase.js:2
notifyUp @ showcase.js:2
setDirty @ showcase.js:2
set value @ showcase.js:2
set @ showcase.js:2
updateCurrentPhase @ showcase.js:2
error @ showcase.js:2
watchErrors @ showcase.js:2
await in watchErrors (async)
init @ showcase.js:2
(anonymous) @ showcase.js:14
Promise.then (async)
then @ showcase.js:14
(anonymous) @ showcase.js:14
Promise.then (async)
loadModule @ showcase.js:14
loadModule @ showcase.js:14
load @ showcase.js:14
loadApplication @ showcase.js:14
(anonymous) @ showcase.js:14
(anonymous) @ showcase.js:14
(anonymous) @ ?m=Ez3YDocMaVx:137
showcase.js:14 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
    at o (showcase.js:14:445750)
    at Module.52061 (833.js:9:25596)
    at Function.o (showcase.js:14:445750)
o @ showcase.js:14
52061 @ 833.js:9
o @ showcase.js:14
await in o (async)
notifyObserver @ showcase.js:2
notifyObservers @ showcase.js:2
notifyObservers @ showcase.js:2
notifyUp @ showcase.js:2
commit @ showcase.js:2
updateCurrentPhase @ showcase.js:2
error @ showcase.js:2
watchErrors @ showcase.js:2
await in watchErrors (async)
init @ showcase.js:2
(anonymous) @ showcase.js:14
Promise.then (async)
then @ showcase.js:14
(anonymous) @ showcase.js:14
Promise.then (async)
loadModule @ showcase.js:14
loadModule @ showcase.js:14
load @ showcase.js:14
loadApplication @ showcase.js:14
(anonymous) @ showcase.js:14
(anonymous) @ showcase.js:14
(anonymous) @ ?m=Ez3YDocMaVx:137

**Comment by mitchcapper** [comment]
Did you use the advanced download option and internal server?

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
