### ISSUE TITLE
JS File downloaded but not known (300.js, 309.js, 393.js, 521.js, 564.js, 633.js, 674.js, 769.js, 856.js, 934.js)

### ISSUE THREAD

**Issue by bhessen** [rebane2001/matterport-dl#53]
https://cdn-1.matterport.com/models/49085fb967d04d92996277bd1d15bfbc/assets/~/{filename}?t=2-XXXXXXXXXXXXXXXXXXXXXXX
Downloading static assets...
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 300.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 309.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 393.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 564.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 633.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 674.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 769.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 856.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 934.js, will download for you though:)
Downloading model info...

**Comment by r3naissance** [comment]
Was about to post this as well but bhessen beat me to it!

**Comment by jtolio** [comment]
same

**Comment by SliceRush** [comment]
Same issue here...

**Comment by RaHaNGS** [comment]
Ditto

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
