### ISSUE TITLE
Seems to be trying to download files with ~ in the URL

### ISSUE THREAD

**Issue by omiq** [rebane2001/matterport-dl#54]
![Screen Shot 2022-05-29 at 15 10 02](https://user-images.githubusercontent.com/3143825/170891528-cd211249-c58a-4ba7-b0db-e1c7f334c361.png)

Running this seems to bork it because of the ~ directory name

**Comment by mitchcapper** [comment]
added an option to fix this for platforms that don't support a ~ folder name.
