### ISSUE TITLE
Oops, model not available. If the problem persists see our troubleshooting guide

### ISSUE THREAD

**Issue by Mattio1990** [rebane2001/matterport-dl#60]
Oops, model not available.
If the problem persists [see our troubleshooting guide](https://support.matterport.com/s/article/Oops-Model-Not-Available)

Download went smoothly, no error, not sure why it is not working. I also tried the --advanced-download option still not working..

in the logs it says "127.0.0.1 - - [14/Jun/2022 13:26:40] code 404, message File not found"

I looked in server logs and it says 

2022-06-14 13:26:40 WARNING  404 error: /favicon.ico may not be downloading everything right

I don't see anything else, any ideas???

**Comment by mitchcapper** [comment]
Dupe of #55

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
