### ISSUE TITLE
The tour is only working for 5 minutes

### ISSUE THREAD

**Issue by mu-ramadan** [rebane2001/matterport-dl#63]
The tour is only working for 5 minutes after that i get error Oops, model not available.

if i re archive it it's always expiring after 5 minutes again 
ive noticed that in models \api\mp\models 
graph_GetSnapshots.json and graph_GetModelDetails.json 

contains "validUntil":"" only 5 minutes I've tried to change it manually to "validUntil":"2099-07-01T13:24:35Z" but still the same

**Comment by mu-ramadan** [comment]
update after changing files url on \api\mp\models\graph_GetModelDetails.json from https://cdn-2.matterport.com to 127.0.0.1:8080 it's working now

**Comment by mitchcapper** [comment]
To confirm if I choose a random model, download it, and leave the browser open for 5 minutes it will throw an error right?   Seems easy enough to fix just want to make sure I understand the repro first.

**Comment by mu-ramadan** [comment]
i'm trying on this model id [ohCrgtmfc29](https://my.matterport.com/show/?m=ohCrgtmfc29)
and other random models with the same results on windows and linux 

1-  i downloaded the tool and and downloaded the model with --advanced-download option  
i've got "Oops, model not available."

2- i downloaded [GetModelDetails.json](https://github.com/mitchcapper/matterport-dl/blob/graph_post_getmodeldetails_add_pr/graph_posts/GetModelDetails.json) file, added it to graph_posts folder
and re archived the model it worked fine.


but if i tried to reopen it again after 5 minutes i get error "Oops, model not available."
to repro try to empty cache and refresh or if open it on private window after more than 5 minutes.
if i re archive it again it's working only for 5 minutes then i get  "Oops, model not available." if i empty cache and refresh or open it in private window.

**Comment by m3ikdev** [comment]
What i see on my side, it's only working 5min because it partially download all file need to work.
Good way to test after you run the download, cut internet of your machine some files still 404 because it still pointing on https://cdn-2.matterport.com/...

Some json and glb file are not download localy like this one
/(model ID)/models/(UID)/assets/mesh_tiles/~/(t).json inside this file you have few URI glb and URI  json files to download localy 
if it could help

**Comment by mu-ramadan** [comment]
thanks @m3ikdev i already did this
i  replaced 
https://cdn-2.matterport.com/ with http://127.0.0.1:(PORT)/ in this two files
/api/mp/models/graph_GetModelDetails.json
/api/mp/models/graph_GetSnapshots.json"

and it's working now but is there's any way to patch the main script to download missing files or replace https://cdn-2.matterport.com/ with http://127.0.0.1:(PORT)/ ?
