### ISSUE TITLE
Error 401: Unauthorized File 

### ISSUE THREAD

**Issue by charliejameslockwood** [rebane2001/matterport-dl#64]
Hi,

I've been applying various fixes in the unmerged PRs to try and archive a model I'm interested in.

It seems to archive, but then when I try to host the files locally using the built in server, I get the "Oops, model is not available" message.

When checking the run_report log and the console in my browser, I see a lot of Errors.

In the run_report log the messages all start HTTP Error 401: Unauthorized file...

In the server log I see one warning
404 error: api/v1/jsonstore/model/trims/{my-id} may not be downloading everything right

In the console the errors are more varied but include:

- 401 Unauthorized..
- No suitable model file found
- Mesh Creation Exception

Any ideas?

**Comment by patricknelson** [comment]
Hmm... I'm having a similar UI error message, however, ho such HTTP requests seem to be emitted (nor received by the server, according to the logs). If you format the source code and check that line, it appears to be reverting to requiring authentication in the JavaScript and they (for some reason, maybe lack of experience or potentially to "throw off the scent") they output "Access denied (403)", even though no actual HTTP request was issued (given 403 is an actual "Forbidden" error code).

![2022-07-08_11-56-21](https://user-images.githubusercontent.com/4269377/178054670-ae447577-fc76-42f1-9175-b15bb26489f1.png)

**Comment by patricknelson** [comment]
Digging a bit deeper I've made _some_ progress and boiled it down to the fact that the script now needs support for a few more graph queries: 

- GetModelDetails
- GetModelPolicies
- GetModelViewPrefetch

I copied the contents of those requests, then stubbed those out in the root `./graph_posts/` directory, swapped out the `[MATTERPORT_MODEL_ID]` placeholder and then re-ran the download and... viola! It's working.  I'll consider issuing a PR, but for now, check out this commit here: https://github.com/rebane2001/matterport-dl/commit/ae18dd07570bd329f99131144b1ee581d09aec43

The only _**issue**_ I'm seeing now is that it's still issuing CDN requests to `matterport.com` when it should be referencing locally cached data, but at least I got past that initial hurdle. I'll need to spend more time over the weekend to figure the rest of that CDN stuff out, though.

**Comment by patricknelson** [comment]
Ok, figured out download of additional assets (`trims`) and also better isolation of resources, ensuring it points to the local server instead of the CDN. Code wise, the last remaining piece is to refactor references to things like `cdn-2.matterport.com` in the cached graph JSON responses (i.e. under `./[MATTERPORT_MODEL_ID]/api/mp/models/graph/graph_*`).

You can see my hacky WIP here: #65

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
