### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by MrOmnes** [rebane2001/matterport-dl#7]
File "C:\Users\33661\Desktop\StreamRunners\╔quipe\KÚvin Comte\matterport-dl.py", line 40
    variants.append(f"{z}_face{face}_{x}_{y}.jpg")
                                                                      ^
SyntaxError: invalid syntax

**Comment by databird** [comment]
You need to use Python3.6 ( f"..." is a Python 3.6 feature )

**Comment by MrOmnes** [comment]
@databird Yes sorry, i notice that too late, it works perfectly right now
