### ISSUE TITLE
Need js (207, 260, 300, 309, 385, 393, 521, 564, 58, 633, 769, 794, 934, 976, 995)

### ISSUE THREAD

**Issue by mazshar** [rebane2001/matterport-dl#70]
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 207.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 260.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 300.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 309.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 385.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 393.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 564.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 58.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 633.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 769.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 794.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 934.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 976.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 995.js, will download for you though:)

**Comment by chrishutchins** [comment]
Had the same issue. Even with the fix from #55 (and also trying @patricknelson's fork) I'm still getting "Oops, model not available."

**Comment by mu-ramadan** [comment]
> Had the same issue. Even with the fix from #55 (and also trying @patricknelson's fork) I'm still getting "Oops, model not available."

try this #66

**Comment by chrishutchins** [comment]
> try this [Matterport-dl](https://github.com/mu-ramadan/matterport-dl)

That worked, thank you!

**Comment by igpit** [comment]
> > Had the same issue. Even with the fix from #55 (and also trying @patricknelson's fork) I'm still getting "Oops, model not available."
> 
> try this [Matterport-dl](https://github.com/mu-ramadan/matterport-dl)

wrong place to answer this here, but i cannot create a issue on your forked project. 

regarding your fix in line 293 in  patchGetModelDetails() hard coding the localServer variable:
as this forces :8080 into the json, running the downloaded project server from any port than 8080 breaks the page. dynamically connection to the server endpoint using e.g. location.port would be nice?

**Comment by noto10** [comment]
> > Had the same issue. Even with the fix from #55 (and also trying @patricknelson's fork) I'm still getting "Oops, model not available."
> 
> try this [Matterport-dl](https://github.com/mu-ramadan/matterport-dl)

I just tried the above and am getting the following output while viewing. Would appreciate any help:


```
View in browser: http://127.0.0.1:8080
127.0.0.1 - - [24/Aug/2022 23:56:26] "GET /fonts/roboto-regular.woff2 HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 57194)
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Program Files\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Program Files\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\Python310\lib\http\server.py", line 658, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Program Files\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Program Files\Python310\lib\http\server.py", line 432, in handle
    self.handle_one_request()
  File "C:\Program Files\Python310\lib\http\server.py", line 420, in handle_one_request
    method()
  File "E:\Users\bluelight\Downloads\matterport-dl-support-new-graph-posts\matterport-dl.py", line 432, in do_GET
    SimpleHTTPRequestHandler.do_GET(self)
  File "C:\Program Files\Python310\lib\http\server.py", line 665, in do_GET
    self.copyfile(f, self.wfile)
  File "C:\Program Files\Python310\lib\http\server.py", line 865, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "C:\Program Files\Python310\lib\shutil.py", line 198, in copyfileobj
    fdst_write(buf)
  File "C:\Program Files\Python310\lib\socketserver.py", line 826, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
----------------------------------------
127.0.0.1 - - [24/Aug/2022 23:56:27] "POST /api/mp/models/graph HTTP/1.1" 200 -
127.0.0.1 - - [24/Aug/2022 23:56:27] "POST /api/v1/event HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /?m=5eVRaArDLJP HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /css/showcase.css HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /css/unsupported_browser.css HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /js/browser-check.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /js/showcase.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /fonts/roboto-regular.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET //api/v2/users/current HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /js/995.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /js/794.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /js/764.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /js/136.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "POST /api/mp/models/graph HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /locale/strings.json HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /fonts/roboto-300.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /fonts/roboto-500.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:38] "GET /?m=5eVRaArDLJP HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:40] "POST /api/mp/models/graph HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:40] "POST /api/v1/event HTTP/1.1" 200 -


```

**Comment by noto10** [comment]
> > Had the same issue. Even with the fix from #55 (and also trying @patricknelson's fork) I'm still getting "Oops, model not available."
> 
> try this [Matterport-dl](https://github.com/mu-ramadan/matterport-dl)

```
I just tried the above and am still getting '**Oops, model not available**' with the following output :

View in browser: http://127.0.0.1:8080
127.0.0.1 - - [24/Aug/2022 23:56:26] "GET /fonts/roboto-regular.woff2 HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 57194)
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Program Files\Python310\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Program Files\Python310\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Program Files\Python310\lib\http\server.py", line 658, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Program Files\Python310\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Program Files\Python310\lib\http\server.py", line 432, in handle
    self.handle_one_request()
  File "C:\Program Files\Python310\lib\http\server.py", line 420, in handle_one_request
    method()
  File "d:\users\archive\matterport-dl-support-new-graph-posts\matterport-dl.py", line 432, in do_GET
    SimpleHTTPRequestHandler.do_GET(self)
  File "C:\Program Files\Python310\lib\http\server.py", line 665, in do_GET
    self.copyfile(f, self.wfile)
  File "C:\Program Files\Python310\lib\http\server.py", line 865, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "C:\Program Files\Python310\lib\shutil.py", line 198, in copyfileobj
    fdst_write(buf)
  File "C:\Program Files\Python310\lib\socketserver.py", line 826, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
----------------------------------------
127.0.0.1 - - [24/Aug/2022 23:56:27] "POST /api/mp/models/graph HTTP/1.1" 200 -
127.0.0.1 - - [24/Aug/2022 23:56:27] "POST /api/v1/event HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /?m=5eVRaArDLJP HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /css/showcase.css HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /css/unsupported_browser.css HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /js/browser-check.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /js/showcase.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /fonts/roboto-regular.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET //api/v2/users/current HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /js/995.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /js/794.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /js/764.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /js/136.js HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "POST /api/mp/models/graph HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /locale/strings.json HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /fonts/roboto-300.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:20] "GET /fonts/roboto-500.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:38] "GET /?m=5eVRaArDLJP HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:40] "POST /api/mp/models/graph HTTP/1.1" 200 -
127.0.0.1 - - [25/Aug/2022 00:00:40] "POST /api/v1/event HTTP/1.1" 200 -

```

**Comment by mu-ramadan** [comment]
> > > Had the same issue. Even with the fix from #55 (and also trying @patricknelson's fork) I'm still getting "Oops, model not available."
> > 
> > 
> > try this [Matterport-dl](https://github.com/mu-ramadan/matterport-dl)
> 
> wrong place to answer this here, but i cannot create a issue on your forked project.
> 
> regarding your fix in line 293 in patchGetModelDetails() hard coding the localServer variable: as this forces :8080 into the json, running the downloaded project server from any port than 8080 breaks the page. dynamically connection to the server endpoint using e.g. location.port would be nice?

Yes, it would be better but I don't know how to do it :"D 
except patching the files every time you run the script to view the tour
I'm waiting for [mitchcapper](https://github.com/mitchcapper) update

**Comment by mu-ramadan** [comment]
> > > Had the same issue. Even with the fix from #55 (and also trying @patricknelson's fork) I'm still getting "Oops, model not available."
> > 
> > 
> > try this [Matterport-dl](https://github.com/mu-ramadan/matterport-dl)
> 
> I just tried the above and am still getting **"Oops, model not available"** with the following output :


delete the script and redownload it again, you must use --advanced-download option and server 127.0.0.1 8080 
you can edit it on matterport-dl.py ` localServer = "http://127.0.0.1:8080"`  if you want to use different server IP address and port and redownload the virtual tour again to update graph_GetModelDetails with the new server and port

**Comment by colinkershaw** [comment]
I was also getting the JavaScript "not known" message, and while I (mis?)understand that is informational (and not exactly an error?), I was getting still "Model not found" so came here to look for possible solutions. 

As per the information in this thread, I downloaded the latest scripts (the whole .zip) from the _mu-ramadan_ fork and re-ran both over the initial Matterport download (to save re-downloading) and also "fresh" (complete download) several times without a successful result.

Running just the latest _mu-ramadan_ fork script I get the following error, which I don't see anyone else reporting (note that _<ID>_ has a valid ID when I actually run it, one that works in the browser):

```
C:\Users\c>>py c:\Users\c\matterport-dl-main\matterport-dl.py "https://my.matterport.com/show/?m=_<ID>_" --advanced-download
Traceback (most recent call last):
  File "C:\Users\ck\Projects\matterport-dl-main\matterport-dl.py", line 612, in <module>
    initiateDownload(pageId)
  File "C:\Users\ck\Projects\matterport-dl-main\matterport-dl.py", line 477, in initiateDownload
    downloadPage(getPageId(url))
  File "C:\Users\ck\Projects\matterport-dl-main\matterport-dl.py", line 467, in downloadPage
    patchGetModelDetails()
  File "C:\Users\ck\Projects\matterport-dl-main\matterport-dl.py", line 294, in patchGetModelDetails
    with open("api/mp/models/graph_GetModelDetails.json", "r", encoding="UTF-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'api/mp/models/graph_GetModelDetails.json'
```

One thing I notice is I don't see any download progress, whereas I do when running the _rebane2001_ script:

```
C:\Users\c>>py c:\Users\c\matterport-dl-main2\matterport-dl.py "https://my.matterport.com/show/?m=_<ID>_" --advanced-download
100%|                                                                | 43350/43350 [19:25<00:00, 37.19it/s]

```

I also notice differences between the results from running the mu-ramadan vs rebane2001 scripts, like different missing files and folders (note this doesn't necessarily mean all the other files and folders are in good shape, simply that they are the binary equal, with the exception of _index.html_ and _run_report.log_ which differ):

Present in rebane2001 results not in mu-ramadan results:
- api\v1\event
- models\...\assets\~\tiles\
- models\...\assets\~\<an_id>_50k.dam
- models\...\assets\<an_id>_50k.dam

Present in mu-ramadan results not in rebane2001 results:

- api\v1\jsonstore\model\trims\
- css\core.css
- models\assets\pan

Thanks in advance for any suggestions :)

Additional info:
Windows 11
Python 3.10.6
Chrome 104.0.5112.102

**Comment by mu-ramadan** [comment]
@colinkershaw  
Download the script from here [Matterport-dl](https://github.com/mu-ramadan/matterport-dl )
Extract the files 
open cmd and cd into matterport-dl-main folder
to download type Ex:  `python3 matterport-dl.py Xmjf0kdfF --advanced-download`
to view it type: `python3 matterport-dl Xmjf0kdfF 127.0.0.1 8080`

**Comment by colinkershaw** [comment]
Thanks @mu-ramadan - that worked! Is the difference that:

1.  the script needs to be run from within the matterport-dl folder? (eg, cd into matterport-dl-main)
2. only the ID should be used and not the full URL? eg,  
- `python3 matterport-dl.py Xmjf0kdfF --advanced-download` vs 
- `python3 matterport-dl.py "https://my.matterport.com/show/?m=Xmjf0kdfF" --advanced-download` 
3. the script was updated?

Or any combination of the above (since they are not mutually exclusive)?

Thanks again! 

PS: Very minor note for others, my Python install is referenced via `python` rather than `python3` so it was:
`python matterport-dl.py Xmjf0kdfF --advanced-download`
which specifically worked for me (with my ID in place of Xmjf0kdfF of course) - just in case you have a different mapping to your Python install too.

**Comment by lalitkumarj** [comment]
I tried the above (with mu-ramadan). The download seems fine, but when I run the server the webpage gets stuck on the loading screen. In the console I see:
```Error: TilesRenderer: Failed to load tileset http://127.0.0.1:8080/models/dc86b046c5fe428c9cdcc80ca6b52070/assets/mesh_tiles/~/3.json?t=2-6b204149dc9cce300ecd7ff5cc0ff6c30fb12781-1665068901-1&k=models%2Fdc86b046c5fe428c9cdcc80ca6b52070%2Fassets%2Fmesh_tiles```

Any ideas?

**Comment by plusFeldt** [comment]
@lalitkumarj it's exactly the same here. Ideas? No.

**Comment by mu-ramadan** [comment]
Can you send me the virtual tour url I'll try to check 

cn3q3gtd@duck.com

**Comment by plusFeldt** [comment]
I'll do, thanks in advance! Please give me some minutes. I just check it again, the download runs currently and fyi these two missing js-files are reported:
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 324.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 378.js, will download for you though:)

**Comment by plusFeldt** [comment]
> @lalitkumarj it's exactly the same here. Ideas? No.

Solved: my fault! Sorry. I used http://localhost:8080, using http://127.0.0.1:8080 in the browser works fine.

**Comment by victorDJ504** [comment]
@mu-ramadan  Thanks for the time spent on this project. I am sucessfully downloading and navigating. Am I right to say that the dollhouse at the moment is not an accurate representation?  also I notice the mattertags which are originally linked to images on a website are showing "unable to load media. The link is private" is this also normal?   THX. I am running latest build.

**Comment by mu-ramadan** [comment]
> @mu-ramadan Thanks for the time spent on this project. I am sucessfully downloading and navigating. Am I right to say that the dollhouse at the moment is not an accurate representation? also I notice the mattertags which are originally linked to images on a website are showing "unable to load media. The link is private" is this also normal? THX. I am running latest build.

the script is  not working with private Url must be public.

**Comment by victorDJ504** [comment]
The link on the mattertag jpg is indeed public, and the matterport model is "unlisted-only people with link" here is a view of the mattertag link in original model...

https://user-images.githubusercontent.com/111089776/215615549-ed630b23-6b9d-4605-8559-d1bcbc23a145.mp4

same mattertag on archived model ( see pic)
https://user-images.githubusercontent.com/111089776/215615592-69929553-fd9a-4afc-b24d-bfa910b27001.png

trying to find if I am doing or configuring anything wrong.  thx!

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
