### ISSUE TITLE
code 404, message File not found

### ISSUE THREAD

**Issue by zhusulai** [rebane2001/matterport-dl#72]
The files were successfully downloaded, but when I try to view the model I'm getting a 404 error. 

```
127.0.0.1 - - [12/Sep/2022 21:35:18] code 404, message File not found
127.0.0.1 - - [12/Sep/2022 21:35:18] "GET /models/4a5e5f7bda6c4c9e80ae02b6db7377ec/assets/mesh_tiles/~/3.json?t=2-5e9d1931c236d0ac9516dc8b6229703df628e83d-1662945510-1&k=models%2F4a5e5f7bda6c4c9e80ae02b6db7377ec%2Fassets%2Fmesh_tiles HTTP/1.1" 404 -
```

I used the latest branch with all the fixes and the url of the model is "https://my.matterport.com/show/?m=teZrGGmjYYr"

**Comment by MetroSynth** [comment]
I'm getting this same error. Download was successful but attempting to run it gives this error for me:
`127.0.0.1 - - [27/Sep/2022 18:10:34] code 404, message File not found
127.0.0.1 - - [27/Sep/2022 18:10:34] "GET /models/78b9dec3f5dd4f4f967fdf3a7739d73d/assets/mesh_tiles/~/3.json?t=2-7224d41e2108198bebe184cd74fa1838f77c670a-1664313520-1&k=models%2F78b9dec3f5dd4f4f967fdf3a7739d73d%2Fassets%2Fmesh_tiles HTTP/1.1" 404 -`

I took a look in the server log and am seeing the following line as well:
`2022-09-27 18:10:34 WARNING  404 error: /models/78b9dec3f5dd4f4f967fdf3a7739d73d/assets/mesh_tiles/~/3.json?t=2-7224d41e2108198bebe184cd74fa1838f77c670a-1664313520-1&k=models%2F78b9dec3f5dd4f4f967fdf3a7739d73d%2Fassets%2Fmesh_tiles may not be downloading everything right`

URL of the model is here:
https://my.matterport.com/show/?m=V3XpAtoVQGB&mls=1

**Comment by MetroSynth** [comment]
Update: Was able to get this working with a manual file edit.
If you take a look in your /api/mp/models/graph_GetModelDetails.json file you'll likely see the tilesets array populated with a bunch of data where none of the older models had any. Example of the new stuff:
```
"tilesets" : [ {
  "status" : "available",
  "tilesetVersion" : "1.2.0",
  "url" : "http://127.0.0.1:8080/models/78b9dec3f5dd4f4f967fdf3a7739d73d/assets/mesh_tiles/~/tileset.json?t=2-7224d41e2108198bebe184cd74fa1838f77c670a-1664313520-1&k=models%2F78b9dec3f5dd4f4f967fdf3a7739d73d%2Fassets%2Fmesh_tiles",
  "urlTemplate" : "http://127.0.0.1:8080/models/78b9dec3f5dd4f4f967fdf3a7739d73d/assets/mesh_tiles/~/<file>?t=2-7224d41e2108198bebe184cd74fa1838f77c670a-1664313520-1&k=models%2F78b9dec3f5dd4f4f967fdf3a7739d73d%2Fassets%2Fmesh_tiles",
  "validUntil" : "2022-09-27T21:18:40Z",
  "tilesetDepth" : 3,
  "tilesetPreset" : "basic1",
  "__typename" : "Tileset"
} ],
```
I deleted all those values and re-loaded the model and it worked fine. Looks like newer content is using a different folder structure and naming convention for their tiles. The model from my example has a created date of 2022-09-15 16:25:15Z in the graph_GetModelDetails.json file FYI, so I would assume this will be the case with newer models. The tilesetVersion of 1.2 also leads me to believe this was just rolled out.

**Comment by Daniel15** [comment]
> I deleted all those values and re-loaded the model and it worked fine.

Thanks @MetroSynth  - This worked for me too.

**Comment by andrewginns** [comment]
For clarity for others my "tilesets" entry looks like this and works after facing the loading issue

```
"tilesets" : [ {

} ],
```

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
