### ISSUE TITLE
NEW FILES

### ISSUE THREAD

**Issue by sbirkmann** [rebane2001/matterport-dl#73]
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 207.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 260.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 300.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 309.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 385.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 393.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 564.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 58.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 633.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 769.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 794.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 934.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 976.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 995.js, will download for you though:)

**Comment by gene1wood** [comment]
Also

```
330.js
39.js
399.js
438.js
62.js
76.js
926.js
933.js
```

**Comment by redstreet** [comment]
+1 to the above. They need to added to [this list](https://github.com/mu-ramadan/matterport-dl/blob/21c51e03e9e14eecd0953be5c544f3426335b754/matterport-dl.py#L159).

**Comment by redstreet** [comment]
Ah, good to know. Edited my comment.

**Comment by sbirkmann** [comment]
Do you have a fix for this?

**Comment by mu-ramadan** [comment]
@sbirkmann  #66

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
