### ISSUE TITLE
Missing dependent js file https://static.matterport.com/webgl-vendors/three/0.139.2/three.min.js

### ISSUE THREAD

**Issue by gene1wood** [rebane2001/matterport-dl#75]
Looks like the current matterport depends on this file

https://static.matterport.com/webgl-vendors/three/0.139.2/three.min.js

which 404s and so the downloaded model doesn't display.

**Comment by gene1wood** [comment]
Thanks! Ya for some reason [this search](https://github.com/rebane2001/matterport-dl/search?q=three.min.js) didn't turn it up in that PR

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
