### ISSUE TITLE
Not known js files

### ISSUE THREAD

**Issue by ravi-ramadoss** [rebane2001/matterport-dl#77]
I tried to download a video but got the below message

JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 309.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 330.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 385.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 39.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 399.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 438.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 58.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 62.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 633.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 76.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 926.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 933.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 934.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 995.js, will download for you though:)

**Comment by arthurlutz** [comment]
Exactly the same here...

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
