### ISSUE TITLE
Unauthorized Access

### ISSUE THREAD

**Issue by abrahamarslan** [rebane2001/matterport-dl#78]
![image](https://user-images.githubusercontent.com/14885767/195548511-5b874364-72f2-4f46-af84-1bd566396ed8.png)

**Comment by optroodt** [comment]
Same issue, different Showcase app version.

![image](https://user-images.githubusercontent.com/1515592/202875839-872a1b77-1b36-47f4-b0ef-84ae4221cfec.png)

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
