### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by nazgulov** [rebane2001/matterport-dl#79]
Hi all, I'm not familiar with Python yet.
Does it worth to invest time to this downloader because it seems nice to download Matterport virtual space?
Nevertheless according to comments here it seems that downloader isn't working.

**Comment by fdd4s** [comment]
Here is my alternative https://github.com/fdd4s/matterport-downloader
Just download the panoramic images, and you can view it later in any panoramic viewer, or just upload as 360º slideshow video to youtube where it'll remain forever for free.
My code just take the panos images, matterport-dl is a more complete alternative.

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
