### ISSUE TITLE
Unknown js files

### ISSUE THREAD

**Issue by plusFeldt** [rebane2001/matterport-dl#80]
Downloading static assets...
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 324.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 378.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 512.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 866.js, will download for you though:)

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
