### ISSUE TITLE
Unknow js files

### ISSUE THREAD

**Issue by MarcosPer** [rebane2001/matterport-dl#81]
Unknow js files. Downloading with advanced option

JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 309.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 324.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 330.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 378.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 385.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 399.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 512.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 58.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 62.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 633.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 76.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 866.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 926.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 933.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 995.js, will download for you though:)

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
