### ISSUE TITLE
Unknow file

### ISSUE THREAD

**Issue by aud-jeremy** [rebane2001/matterport-dl#82]
Hello 

From url : https://my.matterport.com/show/?m=7LdwjVZ4Ltr

With this command line : python matterport-dl.py https://my.matterport.com/show/?m=7LdwjVZ4Ltr --proxy proxy_adress --advanced-download

I have this message :

JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:189.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:324.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:330.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:491.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:512.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:514.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:58.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:62.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:633.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:76.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:837.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:917.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:926.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:933.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:995.js, will download for you though:)

And when i launch the website : 
View in browser: http://127.0.0.1:8080
127.0.0.1 - - [02/Jan/2023 13:43:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:39] "GET /css/showcase.css HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:39] "GET /css/unsupported_browser.css HTTP/1.1"  200 -
127.0.0.1 - - [02/Jan/2023 13:43:39] "GET /js/browser-check.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:39] "GET /js/showcase.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:39] "GET /?m=7LdwjVZ4Ltr HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:39] "GET /js/browser-check.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:39] "GET /js/showcase.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:39] "GET /fonts/roboto-regular.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:39] "GET /js/995.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:39] "GET /js/514.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:39] "GET /js/189.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:39] "GET /js/136.js HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:39] "GET /favicon.ico HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:39] "GET //api/v2/users/current HTTP/1.1" 200 - 
127.0.0.1 - - [02/Jan/2023 13:43:40] "POST /api/mp/models/graph HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:40] "GET /locale/messages/strings_fr.json HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:40] "POST /api/v1/event HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:40] "GET /locale/strings.json HTTP/1.1" 200 -
127.0.0.1 - - [02/Jan/2023 13:43:40] "GET /fonts/roboto-300.woff2 HTTP/1.1" 200-
127.0.0.1 - - [02/Jan/2023 13:43:40] "GET /fonts/roboto-500.woff2 HTTP/1.1" 200-

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
