### ISSUE TITLE
Unknown JS files

### ISSUE THREAD

**Issue by DarylWM** [rebane2001/matterport-dl#86]
Thank you for this tool. I'm downloading with the advanced option and had these missing JS files reported.

JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 189.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 324.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 325.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 330.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 335.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 512.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 514.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 58.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 62.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 633.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 646.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 671.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 837.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 917.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 926.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 933.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 995.js, will download for you though:)

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
