### ISSUE TITLE
Unable to open model

### ISSUE THREAD

**Issue by CarlosMZuluaga** [rebane2001/matterport-dl#87]
I am able to download the files with no issues. However, when I open my browser I get "Oops, model not available". Upon review of the server.log files I get read the messages below:
2023-02-19 17:59:13 INFO     Server started up
2023-02-19 17:59:22 INFO     Redirecting /js/showcase.js => /js/showcase-internal.js as using our internal showcase.js file
2023-02-19 17:59:22 INFO     Redirecting /js/showcase.js => /js/showcase-internal.js as using our internal showcase.js file
2023-02-19 17:59:23 WARNING  404 error: /favicon.ico may not be downloading everything right

I tried both with my Anaconda python and the CMD python and get the same messages.

**Comment by Planchee** [comment]
Same problem here! 

But wondering if that really is the error, as I also get a 403 (access denied):

`Uncaught (in promise) Forbidden: Access denied (403)
    s http://127.0.0.1:8080/js/showcase.js:2
    s http://127.0.0.1:8080/js/showcase.js:2
    a http://127.0.0.1:8080/js/showcase.js:2
    modelExists http://127.0.0.1:8080/js/showcase.js:2
    loginToModel http://127.0.0.1:8080/js/showcase.js:6
    load http://127.0.0.1:8080/js/showcase.js:6
    loadApplication http://127.0.0.1:8080/js/showcase.js:6
    <anonymous> http://127.0.0.1:8080/js/showcase.js:6
    <anonymous> http://127.0.0.1:8080/js/showcase.js:6
    <anonymous> http://127.0.0.1:8080/?m=[model ID]:158`

**Comment by a1gevaldig** [comment]
I am Also getting the "Oops, model not available" message. Any help?

**Comment by cstout1** [comment]
Same here. Cannot view saved page offline (wifi off) either. Page loads a black screen.

**Comment by tomtranc** [comment]
+1 here.  Guessing from the browser's stacktrace, Matterport might have added a call on their JS to call back to server to perform some check which is causing this 403?

`Uncaught (in promise) Forbidden: Access denied (403)
    s http://127.0.0.1:8080/js/showcase.js:2
    s http://127.0.0.1:8080/js/showcase.js:2
    a http://127.0.0.1:8080/js/showcase.js:2
    modelExists http://127.0.0.1:8080/js/showcase.js:2
    loginToModel http://127.0.0.1:8080/js/showcase.js:6
    load http://127.0.0.1:8080/js/showcase.js:6
    loadApplication http://127.0.0.1:8080/js/showcase.js:6
    i http://127.0.0.1:8080/js/showcase.js:6
    <anonymous> http://127.0.0.1:8080/js/showcase.js:6
    <anonymous> http://127.0.0.1:8080/?m=<model-ID>:158`

**Comment by augiephillips** [comment]
Was this ever solved for anyone? I'm having the same issue.

**Comment by Planchee** [comment]
Yes, I got it successfully working with the fork of Mu-ramadam: https://github.com/mu-ramadan/matterport-dl

> (note: this is not the original tool created by rebane2001; it's an updated version by mu-ramadan. The original tool didn't work; THIS updated one is what worked for me!)
Per https://www.reddit.com/r/DataHoarder/comments/nycjj4/release_matterportdl_a_tool_for_archiving/

Let me know if that worked!

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not

**Comment by vaccinemedia** [comment]
@jdstone did you ever manage to server the model using apache?

**Comment by jdstone** [comment]
@vaccinemedia, no, I did not. I kind of gave up on it. After trying for hours and days, it just didn't seem worth it anymore. :( The only other option I thought of was converting the application to a Python Flask app and using Gunicorn to serve as the production web server. But that proved difficult as well. If you figure it out, definitely post in an issue here somewhere.
