### ISSUE TITLE
ValueError: Unrecognised argument(s): encoding

### ISSUE THREAD

**Issue by HeroponRikiBestest** [rebane2001/matterport-dl#9]
Upon trying to run in Linux Mint 20:
`bestest@bestest-ThinkPad-T14-Gen-1:~/matterport-dl$ python3 matterport-dl.py 3rmnPWnWbhh
Traceback (most recent call last):
  File "matterport-dl.py", line 303, in <module>
    initiateDownload(sys.argv[1])
  File "matterport-dl.py", line 238, in initiateDownload
    downloadPage(getPageId(url))
  File "matterport-dl.py", line 201, in downloadPage
    logging.basicConfig(filename='run_report.log', encoding='utf-8', level=logging.DEBUG,  format='%(asctime)s %(levelname)-8s %(message)s',datefmt='%Y-%m-%d %H:%M:%S')
  File "/usr/lib/python3.8/logging/__init__.py", line 2009, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): encoding
`

**Comment by rebane2001** [comment]
What is your Python version? Try upgrading to Python 3.9 or newer if you can.

**Comment by HeroponRikiBestest** [comment]
My python version is 3.8, unfortunately that's the highest linux mint's default python3 package goes; I can install python3.9, but this program requires tqdm to run, and I'm not sure how to use pip3 with something other than the default python3 package.

**Comment by rebane2001** [comment]
python3.x -m pip

**Comment by HeroponRikiBestest** [comment]
Okay, thank you! Sorry to bother you with this. I did have some issues with the downloaded model, but I'll open a new issue for  that
