### ISSUE TITLE
What is the point of the unknown js_files thing?

### ISSUE THREAD

**Issue by dmd** [rebane2001/matterport-dl#91]
What is the purpose of the unknown js_files thing? Why not just append all of them, rather than having a whitelist?

**Comment by mitchcapper** [comment]
fewer download requests to the server although we now have `--brute-js` to try 1->1000.  If you mean why does it detect them and suggest adding to the list? Idea being we might not parse out all the needed JS files so we try to keep an active list of the known JS files as well.   The current DL logic has changed some though so the warning does not still show up.
