### ISSUE TITLE
How can i host the downloaded archives to my website and make it viewable?

### ISSUE THREAD

**Issue by salvecom333** [rebane2001/matterport-dl#92]
How can i host these Matterport archives in a web server to be viewable? I am trying to add one virtual tour to a shopify page and i am stuck. I found a way to upload the archive through ftp to the hostgator account in the public_html folder.(using filezilla) I get a 404 error when i try to access the index.html in the matterport archive folder through the domain. I'm new to this, can someone point me to the right direction to make it work on a hosted web server or make the matterport archives work online so i can refer to it as a link to the shopify page?

Also thank you so much for developing this tool! It would have take me eons to put something like this together! God bless you creators! And Keep up the good work!
1

**Comment by mitchcapper** [comment]
Not quiet yet,  but the latest changes take big steps towards supporting 3rd party servers again.  There is a temporary hack where you could use the internal server behind nginx or similar proxy that should work but the internal server isn't really meant for multi-client.
