### ISSUE TITLE
JS issue?

### ISSUE THREAD

**Issue by Hoss85** [rebane2001/matterport-dl#94]
I am getting the "oops, model not available" message when I try to view locally.  The consensus seems to be that it relates to the unknown JS messages when downloading.  Any help or workaround anyone could provide would absolutely make my day.

Downloading static assets...
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 111.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 145.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 189.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 195.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 217.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 231.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 324.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 325.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 327.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 330.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 335.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 512.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 607.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 62.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 644.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 648.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 662.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 668.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 858.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 933.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 948.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 958.js, will download for you though:)

**Comment by Hoss85** [comment]
Awesome! I can't wait to try it.

**Comment by Hoss85** [comment]
Finally got around and YAY, worked like a charm.  Thanks again for the heads-up!

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
