### ISSUE TITLE
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add:

### ISSUE THREAD

**Issue by it0kkafk** [rebane2001/matterport-dl#97]
Downloading static assets...
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 145.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 217.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 231.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 258.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 324.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 325.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 327.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 330.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 335.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 573.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 607.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 62.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 644.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 646.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 648.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 662.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 668.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 680.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 690.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 793.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 858.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 933.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 948.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 958.js, will download for you though:)
[js.zip](https://github.com/rebane2001/matterport-dl/files/11853307/js.zip)

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
